Feature/approve case shared components
itk-dev-rpa/Eflyt-gokendelse-af-logivaertsflytninger pull request #14
Opened 2024-09-16 11:58 UTC by bakspace-itk

2024-09-24 06:55 UTC, ghbm-itk requested changes

2024-09-24 06:55 UTC, ghbm-itk commented on robot_framework/eflyt.py
> -    create_note(browser, f"{date.today()} Besked fra Robot: Automatisk godkendt.")
I think you forgot this

2024-09-24 11:33 UTC, bakspace-itk commented on robot_framework/eflyt.py
> -    create_note(browser, f"{date.today()} Besked fra Robot: Automatisk godkendt.")
Indeed.

2024-09-24 11:55 UTC, ghbm-itk submitted a review, later dismissed
Hmm

2024-09-25 06:05 UTC, ghbm-itk approved these changes

2024-09-25 07:48 UTC, merged